BACKGROUND_COLOR=(255,230,247)
WINDOW_WIDTH=1000
WINDOW_HEIGHT=500
import pygame

KITCHEN_IMG=pygame.image.load('kitchen.png')
KITCHEN_SIZE=(WINDOW_WIDTH,WINDOW_HEIGHT)
SAUCE_IMG=pygame.image.load('tomato sauce GIF.gif')

TOMATO_IMG=pygame.image.load('tomato sauce GIF.gif')
TOMATO_WIDTH=350
TOMATO_HEIGHT=130
TOMATO_SIZE=(TOMATO_WIDTH,TOMATO_HEIGHT)
TOMATO_INITIAL_X=465
TOMATO_INITIAL_Y=160
TOMATO_START_LOCATION=TOMATO_INITIAL_X, TOMATO_INITIAL_Y

FONT_NAME = "Calibri"
MESSAGE_A = "א"
MESSAGE_B = "ב"
MESSAGE_C = "ג"
MESSAGE_RECIPE = "מתכון"

FONT_SIZE_SMALL = int(0.02 * 500)
FONT_SIZE = int(0.05 * 500)

FONT_LOCATION = (WINDOW_WIDTH/2, 180)
FONT_LOCATION_RECIPE = (1000, 0)

COLOR = (255, 255, 255)


'''PASTA = {"width":PASTA_WIDTH, "height":PASTA_HEIGHT, "obj_x":PASTA_INITIAL_X, "obj_y":PASTA_INITIAL_Y}
POT = {"width":POT_WIDTH, "height":POT_HEIGHT, "obj_x":POT_INITIAL_X, "obj_y":POT_INITIAL_Y}
LID = {"width":, "height":, "obj_x":, "obj_y":}
appearance = [LID, LADLE]'''